/**
 * Voice streaming client with high-resolution latency instrumentation.
 *
 * Every boundary is timestamped using performance.now() (monotonic, ms).
 * A session_id correlates frontend and backend events.
 *
 * Architecture:
 *   Microphone → AudioWorklet → PCM chunks → WebSocket → Backend → Sarvam
 *   Sarvam → Backend → WebSocket → partial/final transcripts → UI
 */

export type StreamEvent =
  | { event: "connected"; latency_ws_connect_ms: number; session_id: string }
  | { event: "vad.speech_start" }
  | { event: "vad.speech_end" }
  | { event: "transcript.partial"; text: string; is_stream_final: boolean }
  | { event: "transcript.final"; text: string; language?: string; language_confidence?: number }
  | { event: "session.end"; audio_duration_s?: number }
  | { event: "error"; message: string; fatal?: boolean }
  | { event: "latency"; total_session_ms: number; audio_bytes_sent: number; backend_breakdown?: Record<string, number> };

export interface VoiceStreamCallbacks {
  onPartial?: (text: string) => void;
  onFinal?: (text: string, language?: string) => void;
  onSpeechStart?: () => void;
  onSpeechEnd?: () => void;
  onConnected?: (latencyMs: number) => void;
  onError?: (message: string, fatal: boolean) => void;
  onLatency?: (totalMs: number, audioBytes: number, backendBreakdown?: Record<string, number>) => void;
  onStateChange?: (state: "idle" | "connecting" | "streaming" | "processing" | "done") => void;
  onTimestamp?: (label: string, ms: number) => void;
}

const API_BASE = (import.meta.env.VITE_API_BASE_URL || "http://localhost:8000").replace(/\/$/, "");
const WS_BASE = API_BASE.replace(/^http/, "ws");

/** Generate a short session ID for correlation. */
function makeSessionId(): string {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 6);
}

export class VoiceStreamClient {
  private ws: WebSocket | null = null;
  private audioCtx: AudioContext | null = null;
  private workletNode: AudioWorkletNode | null = null;
  private sourceNode: MediaStreamAudioSourceNode | null = null;
  private stream: MediaStream | null = null;
  private callbacks: VoiceStreamCallbacks;
  private _state: "idle" | "connecting" | "streaming" | "processing" | "done" = "idle";
  private _lang: string = "en";
  private _sessionId: string = "";
  private _t0: number = 0; // performance.now() at start()
  private _chunkCount: number = 0;
  private _firstChunkSent: boolean = false;
  private _firstPartialReceived: boolean = false;

  constructor(callbacks: VoiceStreamCallbacks) {
    this.callbacks = callbacks;
  }

  get state() { return this._state; }
  get sessionId() { return this._sessionId; }

  private ts(label: string) {
    const ms = performance.now() - this._t0;
    this.callbacks.onTimestamp?.(label, ms);
    console.log(`[Latency] [${this._sessionId}] ${label}: ${ms.toFixed(1)}ms`);
    return ms;
  }

  private setState(s: typeof this._state) {
    this._state = s;
    this.callbacks.onStateChange?.(s);
  }

  async start(lang: string = "en") {
    if (this._state !== "idle") return;
    this._lang = lang;
    this._sessionId = makeSessionId();
    this._t0 = performance.now();
    this._chunkCount = 0;
    this._firstChunkSent = false;
    this._firstPartialReceived = false;
    this.setState("connecting");
    this.ts("T0: start() called");

    try {
      // 1. Get microphone stream.
      this.stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      this.ts("T1: getUserMedia completed");

      // 2. Create AudioContext at 16kHz.
      this.audioCtx = new AudioContext({ sampleRate: 16000 });
      this.ts("T2: AudioContext created");

      // 3. Load AudioWorklet processor.
      await this.audioCtx.audioWorklet.addModule("/pcm-processor.js");
      this.ts("T3: AudioWorklet loaded");

      // 4. Create nodes.
      this.sourceNode = this.audioCtx.createMediaStreamSource(this.stream);
      this.workletNode = new AudioWorkletNode(this.audioCtx, "pcm-processor");
      this.ts("T4: Nodes created");

      // 5. Listen for PCM chunks from the worklet.
      this.workletNode.port.onmessage = (e: MessageEvent<ArrayBuffer>) => {
        this._chunkCount++;
        if (!this._firstChunkSent) {
          this._firstChunkSent = true;
          this.ts("T6: first PCM chunk generated by worklet");
        }
        if (this.ws?.readyState === WebSocket.OPEN) {
          this.ws.send(e.data);
          if (this._chunkCount === 1) {
            this.ts("T7: first PCM chunk sent over WebSocket");
          }
        }
      };

      // 6. Connect: mic → worklet.
      this.sourceNode.connect(this.workletNode);
      this.ts("T5: AudioWorklet connected (mic → worklet)");

      // 7. Open WebSocket to backend.
      const wsUrl = `${WS_BASE}/voice/stream`;
      console.log(`[Latency] [${this._sessionId}] WebSocket URL: ${wsUrl}`);
      this.ws = new WebSocket(wsUrl);

      this.ws.onopen = () => {
        this.ts("T8: WebSocket opened");
        // Send start event with language and session_id.
        this.ws!.send(JSON.stringify({
          event: "start",
          lang: this._lang,
          session_id: this._sessionId,
          t0_browser: this._t0,
        }));
        this.ts("T9: start event sent");
      };

      this.ws.onmessage = (e: MessageEvent) => {
        try {
          const data = JSON.parse(e.data);
          this.handleEvent(data);
        } catch { /* ignore parse errors */ }
      };

      this.ws.onclose = (e) => {
        this.ts(`WebSocket closed code=${e.code} reason="${e.reason}"`);
        this.stop();
      };

      this.ws.onerror = (e) => {
        console.error(`[Latency] [${this._sessionId}] WebSocket error: URL=${wsUrl} readyState=${this.ws?.readyState}`);
        this.callbacks.onError?.(
          `WebSocket connection failed. URL: ${wsUrl}. Check that the backend is running and supports WebSocket upgrades.`,
          true,
        );
        this.stop();
      };

    } catch (err: any) {
      this.ts(`ERROR: ${err.message}`);
      this.callbacks.onError?.(err.message || "Failed to start streaming", true);
      this.stop();
    }
  }

  private handleEvent(data: any) {
    switch (data.event) {
      case "connected":
        this.setState("streaming");
        this.ts(`T10: backend connected (Sarvam WS in ${data.latency_ws_connect_ms}ms)`);
        this.callbacks.onConnected?.(data.latency_ws_connect_ms);
        break;
      case "vad.speech_start":
        this.ts("T11: VAD speech_start");
        this.callbacks.onSpeechStart?.();
        break;
      case "vad.speech_end":
        this.ts("T13: VAD speech_end");
        this.callbacks.onSpeechEnd?.();
        this.setState("processing");
        break;
      case "transcript.partial":
        if (!this._firstPartialReceived) {
          this._firstPartialReceived = true;
          this.ts("T12: FIRST partial transcript received");
        }
        this.callbacks.onPartial?.(data.text);
        break;
      case "transcript.final":
        this.ts("T14: FINAL transcript received");
        this.callbacks.onFinal?.(data.text, data.language);
        this.setState("done");
        break;
      case "session.end":
        this.ts("session.end");
        this.stop();
        break;
      case "error":
        this.ts(`ERROR: ${data.message}`);
        this.callbacks.onError?.(data.message, data.fatal ?? false);
        if (data.fatal) this.stop();
        break;
      case "latency":
        this.ts(`LATENCY: total=${data.total_session_ms}ms, bytes=${data.audio_bytes_sent}`);
        this.callbacks.onLatency?.(data.total_session_ms, data.audio_bytes_sent, data.backend_breakdown);
        break;
    }
  }

  /** Signal end of speech — Sarvam will finalize the transcript. */
  stopRecording() {
    this.ts("stopRecording() called");
    if (this.ws?.readyState === WebSocket.OPEN) {
      this.ws.send(JSON.stringify({ event: "stop" }));
    }
    this.workletNode?.port.postMessage("stop");
  }

  /** Full teardown: stop mic, close WS, release resources. */
  stop() {
    try { this.workletNode?.port.postMessage("stop"); } catch { /* */ }
    try { this.sourceNode?.disconnect(); } catch { /* */ }
    try { this.workletNode?.disconnect(); } catch { /* */ }
    try { this.audioCtx?.close(); } catch { /* */ }
    try { this.stream?.getTracks().forEach(t => t.stop()); } catch { /* */ }
    try { this.ws?.close(); } catch { /* */ }

    this.ws = null;
    this.audioCtx = null;
    this.workletNode = null;
    this.sourceNode = null;
    this.stream = null;

    if (this._state !== "idle") {
      this.ts("stop() — session ended");
      this.setState("idle");
    }
  }
}
